In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
df = pd.read_csv("C:\\Users\\vanmu\\copperbelt-mineral-prospectivity\\data\\copperbelt_dataset.csv")
df.head()

,id,left,top,right,bottom,row_index,col_index,Tract_ID_c,Tract_name,Group_name,...,nearest_y,Tract_ID,n_2,distance_2,feature_x_,feature_y_,nearest_x_,nearest_y_,centroid_x,centroid_y
0,4825.0,525140.0118,8.507300e+06,530140.0118,8.502300e+06,71.0,49.0,NaN,NaN,NaN,...,8.570173e+06,5.0,1.0,0.000000,529831.200491,8.502635e+06,529831.200491,8.502635e+06,529911.713578,8.502460e+06
1,4826.0,525140.0118,8.502300e+06,530140.0118,8.497300e+06,72.0,49.0,NaN,NaN,NaN,...,8.570173e+06,5.0,1.0,0.000000,528854.600245,8.497419e+06,528854.600245,8.497419e+06,529382.796539,8.499679e+06
2,4827.0,525140.0118,8.497300e+06,530140.0118,8.492300e+06,73.0,49.0,NaN,NaN,NaN,...,8.570173e+06,5.0,1.0,0.000000,530020.950180,8.495184e+06,530020.950180,8.495184e+06,529694.510138,8.496493e+06
3,4922.0,530140.0118,8.507300e+06,535140.0118,8.502300e+06,71.0,50.0,NaN,NaN,NaN,...,8.570173e+06,5.0,1.0,0.000000,533326.530061,8.503237e+06,533326.530061,8.503237e+06,533039.846413,8.502730e+06
4,4923.0,530140.0118,8.502300e+06,535140.0118,8.497300e+06,72.0,50.0,NaN,NaN,NaN,...,8.570173e+06,5.0,1.0,382.269548,530140.011800,8.502300e+06,530075.134214,8.502677e+06,532640.011800,8.499800e+06

In [27]:
print("shnape:", df.shape)

shnape: (2108, 53)

In [9]:
df.info

<bound method DataFrame.info of           id         left           top        right        bottom  row_index  \
0     4825.0  525140.0118  8.507300e+06  530140.0118  8.502300e+06       71.0
1     4826.0  525140.0118  8.502300e+06  530140.0118  8.497300e+06       72.0
2     4827.0  525140.0118  8.497300e+06  530140.0118  8.492300e+06       73.0
3     4922.0  530140.0118  8.507300e+06  535140.0118  8.502300e+06       71.0
4     4923.0  530140.0118  8.502300e+06  535140.0118  8.497300e+06       72.0
...      ...          ...           ...          ...           ...        ...
2103  1173.0  340140.0118  8.822300e+06  345140.0118  8.817300e+06        8.0
2104  1173.0  340140.0118  8.822300e+06  345140.0118  8.817300e+06        8.0
2105  1174.0  340140.0118  8.817300e+06  345140.0118  8.812300e+06        9.0
2106  1175.0  340140.0118  8.812300e+06  345140.0118  8.807300e+06       10.0
2107     NaN          NaN           NaN          NaN           NaN        NaN

      col_index  Tract_ID_c  Tract_name  Group_name  ...     nearest_y  \
0          49.0         NaN         NaN         NaN  ...  8.570173e+06
1          49.0         NaN         NaN         NaN  ...  8.570173e+06
2          49.0         NaN         NaN         NaN  ...  8.570173e+06
3          50.0         NaN         NaN         NaN  ...  8.570173e+06
4          50.0         NaN         NaN         NaN  ...  8.570173e+06
...         ...         ...         ...         ...  ...           ...
2103       12.0         2.0         2.0         2.0  ...  8.818837e+06
2104       12.0         2.0         2.0         2.0  ...  8.818846e+06
2105       12.0         NaN         NaN         NaN  ...  8.818837e+06
2106       12.0         NaN         NaN         NaN  ...  8.808898e+06
2107        NaN         NaN         NaN         NaN  ...           NaN

      Tract_ID  n_2  distance_2     feature_x_    feature_y_     nearest_x_  \
0          5.0  1.0    0.000000  529831.200491  8.502635e+06  529831.200491
1          5.0  1.0    0.000000  528854.600245  8.497419e+06  528854.600245
2          5.0  1.0    0.000000  530020.950180  8.495184e+06  530020.950180
3          5.0  1.0    0.000000  533326.530061  8.503237e+06  533326.530061
4          5.0  1.0  382.269548  530140.011800  8.502300e+06  530075.134214
...        ...  ...         ...            ...           ...            ...
2103       2.0  1.0    0.000000  340170.524662  8.820324e+06  340170.524662
2104       2.0  1.0    0.000000  340170.524662  8.820324e+06  340170.524662
2105       2.0  1.0    0.000000  340737.146077  8.817260e+06  340737.146077
2106       2.0  1.0    0.000000  340990.063369  8.807363e+06  340990.063369
2107       NaN  NaN         NaN            NaN           NaN            NaN

        nearest_y_     centroid_x    centroid_y
0     8.502635e+06  529911.713578  8.502460e+06
1     8.497419e+06  529382.796539  8.499679e+06
2     8.495184e+06  529694.510138  8.496493e+06
3     8.503237e+06  533039.846413  8.502730e+06
4     8.502677e+06  532640.011800  8.499800e+06
...            ...            ...           ...
2103  8.820324e+06  340665.263328  8.819073e+06
2104  8.820324e+06  340665.263328  8.819073e+06
2105  8.817260e+06  340373.197698  8.817042e+06
2106  8.807363e+06  342949.119215  8.807517e+06
2107           NaN            NaN           NaN

[2108 rows x 53 columns]>

In [28]:
df.describe()

,id,left,top,right,bottom,row_index,col_index,Tract_ID_c,Tract_name,Group_name,...,nearest_y,Tract_ID,n_2,distance_2,feature_x_,feature_y_,nearest_x_,nearest_y_,centroid_x,centroid_y
count,2107.000000,2107.000000,2.107000e+03,2107.000000,2.107000e+03,2107.000000,2107.000000,210.000000,210.000000,210.000000,...,2.107000e+03,2107.000000,2107.000000,2107.000000,2107.000000,2.107000e+03,2107.000000,2.107000e+03,2107.000000,2.107000e+03
mean,4947.321785,533103.941558,8.668192e+06,538103.941558,8.663192e+06,38.821547,50.592786,1.704762,1.704762,1.704762,...,8.668075e+06,3.445657,1.079260,458.442870,535595.477734,8.665765e+06,535591.863731,8.665775e+06,535583.616858,8.665686e+06
std,1980.200660,101010.834230,1.348659e+05,101010.834230,1.348659e+05,26.973175,20.202167,1.061946,1.061946,1.061946,...,1.320692e+05,1.488246,0.277148,1884.246588,100932.965331,1.349041e+05,100968.722536,1.349238e+05,100949.008773,1.348483e+05
min,17.000000,280140.011800,8.382300e+06,285140.011800,8.377300e+06,0.000000,0.000000,1.000000,1.000000,1.000000,...,8.413382e+06,1.000000,1.000000,0.000000,280173.400029,8.378397e+06,280173.400029,8.378397e+06,282674.822654,8.380251e+06
25%,3495.500000,460140.011800,8.557300e+06,465140.011800,8.552300e+06,14.500000,36.000000,1.000000,1.000000,1.000000,...,8.570173e+06,2.000000,1.000000,0.000000,460157.963246,8.552464e+06,460157.963246,8.552581e+06,460678.751563,8.554192e+06
50%,5606.000000,565140.011800,8.692300e+06,570140.011800,8.687300e+06,34.000000,57.000000,1.000000,1.000000,1.000000,...,8.671372e+06,3.000000,1.000000,0.000000,570138.131463,8.687392e+06,569357.763755,8.687392e+06,569518.067404,8.688981e+06
75%,6436.500000,610140.011800,8.789800e+06,615140.011800,8.784800e+06,61.000000,66.000000,2.000000,2.000000,2.000000,...,8.786651e+06,5.000000,1.000000,0.000000,610140.011800,8.787300e+06,610216.579671,8.787298e+06,610580.330118,8.787199e+06
max,8500.000000,715140.011800,8.862300e+06,720140.011800,8.857300e+06,96.000000,87.000000,5.000000,5.000000,5.000000,...,8.837892e+06,5.000000,3.000000,17699.103442,715653.649634,8.860380e+06,715653.649634,8.860380e+06,715464.824670,8.859512e+06

In [29]:
df["deposit_present"] = (df["deposit_ct"]>0).astype(int)

df["deposit_present"].value_counts()

deposit_present
0    1898
1     210
Name: count, dtype: int64

In [30]:
df = df.rename(columns={
    "distance": "distance_to_deposit",
    "distance_2": "distance_to_tract_boundary"
})

df.head()

,id,left,top,right,bottom,row_index,col_index,Tract_ID_c,Tract_name,Group_name,...,Tract_ID,n_2,distance_to_tract_boundary,feature_x_,feature_y_,nearest_x_,nearest_y_,centroid_x,centroid_y,deposit_present
0,4825.0,525140.0118,8.507300e+06,530140.0118,8.502300e+06,71.0,49.0,NaN,NaN,NaN,...,5.0,1.0,0.000000,529831.200491,8.502635e+06,529831.200491,8.502635e+06,529911.713578,8.502460e+06,0
1,4826.0,525140.0118,8.502300e+06,530140.0118,8.497300e+06,72.0,49.0,NaN,NaN,NaN,...,5.0,1.0,0.000000,528854.600245,8.497419e+06,528854.600245,8.497419e+06,529382.796539,8.499679e+06,0
2,4827.0,525140.0118,8.497300e+06,530140.0118,8.492300e+06,73.0,49.0,NaN,NaN,NaN,...,5.0,1.0,0.000000,530020.950180,8.495184e+06,530020.950180,8.495184e+06,529694.510138,8.496493e+06,0
3,4922.0,530140.0118,8.507300e+06,535140.0118,8.502300e+06,71.0,50.0,NaN,NaN,NaN,...,5.0,1.0,0.000000,533326.530061,8.503237e+06,533326.530061,8.503237e+06,533039.846413,8.502730e+06,0
4,4923.0,530140.0118,8.502300e+06,535140.0118,8.497300e+06,72.0,50.0,NaN,NaN,NaN,...,5.0,1.0,382.269548,530140.011800,8.502300e+06,530075.134214,8.502677e+06,532640.011800,8.499800e+06,0

In [31]:
df["log_distance_to_deposit"] = np.log1p(df["distance_to_deposit"])

In [32]:
df.to_csv("C:\\Users\\vanmu\\copperbelt-mineral-prospectivity\\data\\copperbelt_dataset_clean.csv")

In [33]:
df[["distance_to_deposit", "distance_to_tract_boundary"]].describe()

       distance_to_deposit  distance_to_tract_boundary
count          2107.000000                 2107.000000
mean          18985.327470                  458.442870
std           21683.472254                 1884.246588
min               0.000000                    0.000000
25%            3206.932651                    0.000000
50%           11295.745286                    0.000000
75%           26282.028647                    0.000000
max          102313.657838                17699.103442